config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "base#index"
    resources :users do
      resources :permissions
      put "permissions", to: "permissions#set",
                         as: "set_permissions"
    end
  end
  
  delete "/signout", to: "sessions#destroy", as: "signout"

  

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  get "projects/hello"
  root "projects#index"
  resources :projects do
    resources :tickets
  end
  resources :users

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
  mount_uploader :asset, AssetUploader
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	before_action :require_signin!
	before_action :set_project
	before_action :set_ticket, only: [:show, :edit, :update, :destroy]
	before_action :authorize_create!, only: [:new, :create]
	before_action :authorize_update!, only: [:edit, :update]
	before_action :authorize_delete!, only: :destroy

	def index
		@ticket = @project.tickets.all
	end
	def new
		@ticket = @project.tickets.build
	end

	def create
		@ticket = @project.tickets.build(ticket_params)
		@ticket.user = current_user
		if @ticket.save
			flash[:notice] = "Ticket has been created."
			redirect_to [@project, @ticket]
		else
			flash[:alert] = "Ticket has not been created."
			render "new"
		end
	end

	def show
	end
	
	def edit
	end

	def update
		if @ticket.update(ticket_params)
			flash[:notice] = "Ticket has been updated."
			redirect_to [@project, @ticket]
		else
			flash[:alert] = "Ticket has not been updated."
			render action: "edit"
		end
	end
	
	def destroy
		@ticket.destroy
		flash[:notice] = "Ticket has been deleted."
		redirect_to @project
	end

	private
		def set_project
			@project = Project.for(current_user).find(params[:project_id])
			rescue ActiveRecord::RecordNotFound
			flash[:alert] = "The project you were looking " +
			"for could not be found."
			redirect_to root_path
		end
		def set_ticket
			@ticket = @project.tickets.find(params[:id])
		end
		def ticket_params
			params.require(:ticket).permit(:title, :description, :asset)
		end
		def authorize_create!
			if !current_user.admin? && cannot?("create tickets".to_sym, @project)
				flash[:alert] = "You cannot create tickets on this project."
				redirect_to @project
			end
		end
		def authorize_update!
			if !current_user.admin? && cannot?("edit tickets".to_sym, @project)
				flash[:alert] = "You cannot edit tickets on this project."
				redirect_to @project
			end
		end
		def authorize_delete!
			if !current_user.admin? && cannot?(:"delete tickets", @project)
				flash[:alert] = "You cannot delete tickets from this project."
				redirect_to @project
			end
		end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket], html: { multipart: true } do |f| %>
	<% if @ticket.errors.any? %>
		<div id="error_explanation">
		<h2><%= pluralize(@ticket.errors.count, "error") %>
		prohibited this ticket from being saved:</h2>
		<ul>
		<% @ticket.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
		</ul>
		</div>
	<% end %>
	<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	</p>
	<p>
	<%= f.label :description %><br>
	<%= f.text_area :description %>
	</p>
	<p>
	<%= f.label :asset, "File" %><br>
	<%= f.file_field :asset %>
	</p>
	<%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

app/views/tickets/index.html.erb
<h2>Ticket list</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
   	<% @ticket.each do |ticket| %>
      <tr>
        <td><%= link_to ticket.title, project_ticket_path(ticket.project_id, 
              ticket.id)%></td>
        <td><%=ticket.description%></td>
      </tr>
    <% end %>
  </tbody>
</table><br><br>

<% authorized?(:"create tickets", @project) do %>
  <%= link_to "New Ticket", new_project_ticket_path(@project) %>
<% end %>
<%= link_to "Back",projects_path %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %><br><br>
<%= link_to 'Back', project_tickets_path(@project) %>

app/views/tickets/show.html.erb
<div id='ticket'>
	<br>
	<span id='author'>
		 Created by <%= @ticket.user.email %>
	</span>
	<h2>Name::</h2><%= @ticket.title %>
	<h2>Description::</h2><%= simple_format(@ticket.description) %>
	<% if @ticket.asset.present? %>
		<h3>Attached File</h3>
		<div class="asset">
		<p>
			<%= link_to File.basename(@ticket.asset.path),
			@ticket.asset.url %>
		</p>
		<p><small><%= number_to_human_size(@ticket.asset.size) %>
		</small></p>
		</div>
	<% end %>
	<%= authorized?("edit tickets", @project) do %>
		<%= link_to "Edit Ticket", [:edit, @project, @ticket] %>
	<% end %>||
	<% authorized?("delete tickets", @project) do %>
		<%= link_to "Delete Ticket", [@project, @ticket], method: :delete,
		data: { confirm: "Are you sure you want to delete this ticket?"} %>
	<% end %>
</div>

<%= link_to 'Back', project_tickets_path(@project) %>

<!-- remove list of all ticket code -->